-- The Queue — Official Communities Seed
-- Run this in Supabase SQL Editor.
-- Cleans up any duplicate-named official communities first, then inserts.

-- Remove any existing official communities that will be re-seeded
-- so name duplicates from prior partial seeds are wiped cleanly.
DELETE FROM communities WHERE is_official = true;

INSERT INTO communities (slug, name, description, is_official, member_count, parent_slug, creator_user_id)
VALUES

  -- ── GENRES ────────────────────────────────────────────────────────────────
  ('hip-hop',          'Hip Hop',          'Everything hip hop — bars, beats, culture.',                              true, 0, null, null),
  ('rb',               'R&B',              'Rhythm & Blues from classic to contemporary.',                            true, 0, null, null),
  ('soul',             'Soul',             'Soulful music, deep grooves, and real emotion.',                          true, 0, null, null),
  ('funk',             'Funk',             'The one. The funk.',                                                      true, 0, null, null),
  ('gospel',           'Gospel',           'Sacred music, praise, and worship.',                                      true, 0, null, null),
  ('neo-soul',         'Neo Soul',         'The smooth intersection of soul, R&B, and jazz.',                         true, 0, null, null),
  ('afrobeats',        'Afrobeats',        'The global sound of Africa — Afrobeats, Afropop, and beyond.',            true, 0, null, null),
  ('amapiano',         'Amapiano',         'South African log drum and piano-driven house.',                          true, 0, null, null),
  ('dancehall',        'Dancehall',        'Jamaican dancehall — from Kingston to the world.',                        true, 0, null, null),
  ('reggae',           'Reggae',           'Roots, culture, and conscious music.',                                    true, 0, null, null),
  ('soca',             'Soca',             'Caribbean soca — Trinidad, Barbados, and the islands.',                   true, 0, null, null),
  ('house',            'House',            'Four-on-the-floor house music in all its forms.',                         true, 0, null, null),
  ('techno',           'Techno',           'Underground techno — Detroit, Berlin, and beyond.',                       true, 0, null, null),
  ('edm',              'EDM',              'Electronic dance music — festivals, drops, and anthems.',                 true, 0, null, null),
  ('drum-and-bass',    'Drum & Bass',      'High-energy DnB, jungle, and liquid.',                                   true, 0, null, null),
  ('dubstep',          'Dubstep',          'Heavy bass music from the UK underground.',                               true, 0, null, null),
  ('jungle',           'Jungle',           '90s jungle and its descendants.',                                         true, 0, null, null),
  ('jersey-club',      'Jersey Club',      'Newark and Jersey City''s signature club sound.',                         true, 0, null, null),
  ('bounce',           'Bounce',           'New Orleans bounce — the sound of the city.',                             true, 0, null, null),
  ('footwork',         'Footwork',         'Chicago footwork and juke.',                                              true, 0, null, null),
  ('grime',            'Grime',            'UK grime — MCs, 140 BPM, and road rap.',                                 true, 0, null, null),
  ('rock',             'Rock',             'Rock music across all eras and subgenres.',                               true, 0, null, null),
  ('alternative',      'Alternative',      'Alt rock, college radio, and everything in between.',                     true, 0, null, null),
  ('indie',            'Indie',            'Independent music — lo-fi, dream pop, bedroom pop.',                      true, 0, null, null),
  ('punk',             'Punk',             'Punk rock, post-punk, and the DIY spirit.',                               true, 0, null, null),
  ('metal',            'Metal',            'Heavy metal in all its forms.',                                           true, 0, null, null),
  ('grunge',           'Grunge',           'Seattle sound and 90s grunge.',                                           true, 0, null, null),
  ('classic-rock',     'Classic Rock',     'The legends — 60s, 70s, and 80s rock.',                                  true, 0, null, null),
  ('emo',              'Emo',              'Emo, pop-punk, and emotional hardcore.',                                   true, 0, null, null),
  ('pop',              'Pop',              'Pop music — mainstream and everything adjacent.',                          true, 0, null, null),
  ('synth-pop',        'Synth-Pop',        'Synthesizers, new wave, and electronic pop.',                             true, 0, null, null),
  ('k-pop',            'K-Pop',            'Korean pop — groups, solos, and the culture.',                            true, 0, null, null),
  ('j-pop',            'J-Pop',            'Japanese pop music and its many subgenres.',                              true, 0, null, null),
  ('latin-pop',        'Latin Pop',        'Spanish-language pop from across the Americas.',                          true, 0, null, null),
  ('country',          'Country',          'Country music — classic, modern, and everything in between.',              true, 0, null, null),
  ('bluegrass',        'Bluegrass',        'Acoustic string music rooted in Appalachian tradition.',                  true, 0, null, null),
  ('americana',        'Americana',        'Roots music, Americana, and the American songbook.',                      true, 0, null, null),
  ('folk',             'Folk',             'Folk music — storytelling, acoustic, and traditional.',                   true, 0, null, null),
  ('reggaeton',        'Reggaeton',        'Perreo, dembow, and Latin urban from Puerto Rico to the world.',          true, 0, null, null),
  ('latin-trap',       'Latin Trap',       'Spanish-language trap and Latin urban.',                                  true, 0, null, null),
  ('salsa',            'Salsa',            'Salsa — New York, Cuban, and Colombian styles.',                          true, 0, null, null),
  ('bachata',          'Bachata',          'Dominican bachata — traditional and modern.',                             true, 0, null, null),
  ('cumbia',           'Cumbia',           'Colombian cumbia and its Latin American offshoots.',                      true, 0, null, null),
  ('jazz',             'Jazz',             'Jazz in all forms — bebop, fusion, standards, and beyond.',               true, 0, null, null),
  ('blues',            'Blues',            'Delta blues, Chicago blues, and electric blues.',                         true, 0, null, null),
  ('classical',        'Classical',        'Orchestral, chamber, opera, and contemporary classical.',                 true, 0, null, null),
  ('bossa-nova',       'Bossa Nova',       'Brazilian bossa nova and MPB.',                                           true, 0, null, null),
  ('afro-cuban',       'Afro-Cuban',       'Afro-Cuban rhythms, son, guaguancó, and more.',                          true, 0, null, null),
  ('highlife',         'Highlife',         'West African highlife — Ghana, Nigeria, and beyond.',                     true, 0, null, null),
  ('fela',             'Fela',             'Afrobeat in the tradition of Fela Kuti.',                                 true, 0, null, null),
  ('arabic-pop',       'Arabic Pop',       'Arabic-language pop music from across the Arab world.',                   true, 0, null, null),
  ('indian-classical', 'Indian Classical', 'Hindustani and Carnatic classical music.',                                true, 0, null, null),

  -- ── US REGIONS ────────────────────────────────────────────────────────────
  ('south',            'South',            'Southern music culture — rap, country, gospel, and soul.',                true, 0, null, null),
  ('houston',          'Houston',          'H-Town — chopped and screwed, trap, and Texas rap.',                      true, 0, null, null),
  ('atlanta',          'Atlanta',          'ATL — trap, R&B, and the capital of Black music.',                        true, 0, null, null),
  ('memphis',          'Memphis',          'Memphis rap, Three 6 Mafia, and the underground.',                        true, 0, null, null),
  ('new-orleans',      'New Orleans',      'NOLA bounce, brass band, jazz, and second line.',                         true, 0, null, null),
  ('miami',            'Miami',            'Miami bass, club music, and Florida sound.',                              true, 0, null, null),
  ('west-coast',       'West Coast',       'West Coast rap, G-funk, and California sound.',                           true, 0, null, null),
  ('la',               'LA',               'Los Angeles — rap, pop, Latin, and all things LA.',                       true, 0, null, null),
  ('bay-area',         'Bay Area',         'Bay Area hyphy, rap, and the NorCal scene.',                              true, 0, null, null),
  ('east-coast',       'East Coast',       'East Coast rap, boom bap, and New York influence.',                       true, 0, null, null),
  ('nyc',              'NYC',              'New York City — hip hop birthplace, jazz capital, all genres.',            true, 0, null, null),
  ('midwest',          'Midwest',          'Midwest rap, house music, and heartland sound.',                           true, 0, null, null),
  ('chicago',          'Chicago',          'Chicago drill, house, gospel, and soul.',                                 true, 0, null, null),
  ('detroit',          'Detroit',          'Detroit techno, Motown, and the Motor City sound.',                       true, 0, null, null),
  ('dmv',              'DMV',              'DC, Maryland, Virginia — go-go, DMV rap, and the culture.',               true, 0, null, null),

  -- ── INTERNATIONAL REGIONS ─────────────────────────────────────────────────
  ('uk',               'UK',               'UK music — grime, drill, garage, drum & bass, and more.',                 true, 0, null, null),
  ('london',           'London',           'London''s music scene — the most diverse in the world.',                  true, 0, null, null),
  ('nigeria',          'Nigeria',          'Nigerian music — Afrobeats, Afropop, and highlife.',                      true, 0, null, null),
  ('ghana',            'Ghana',            'Ghanaian highlife, hiplife, and Afrobeats.',                               true, 0, null, null),
  ('south-africa',     'South Africa',     'South African amapiano, kwaito, and gqom.',                               true, 0, null, null),
  ('jamaica',          'Jamaica',          'Jamaican dancehall, reggae, and dub.',                                    true, 0, null, null),
  ('trinidad',         'Trinidad',         'Trinidadian soca, calypso, and carnival music.',                          true, 0, null, null),
  ('brazil',           'Brazil',           'Brazilian funk, bossa nova, samba, and baile funk.',                      true, 0, null, null),
  ('puerto-rico',      'Puerto Rico',      'Puerto Rican reggaeton, salsa, and Latin trap.',                          true, 0, null, null),
  ('colombia',         'Colombia',         'Colombian cumbia, vallenato, and Latin urban.',                           true, 0, null, null),
  ('mexico',           'Mexico',           'Mexican regional, norteño, corridos, and urban.',                         true, 0, null, null),
  ('france',           'France',           'French music — French rap, French house, and chanson.',                   true, 0, null, null),
  ('japan',            'Japan',            'Japanese music — J-Pop, J-Rock, and city pop.',                           true, 0, null, null),
  ('korea',            'Korea',            'Korean music — K-Pop, K-R&B, and Korean hip hop.',                        true, 0, null, null),
  ('global',           'Global',           'Music without borders — world music and cross-cultural sounds.',           true, 0, null, null),

  -- ── VIBES ─────────────────────────────────────────────────────────────────
  ('late-night',       'Late Night',       'Music for after midnight — the late night session.',                       true, 0, null, null),
  ('chill-vibes',      'Chill Vibes',      'Easy listening, lo-fi, and music to decompress to.',                      true, 0, null, null),
  ('workout',          'Workout',          'High-energy music to push through your reps.',                             true, 0, null, null),
  ('road-trip',        'Road Trip',        'Windows down, volume up — the ultimate road trip playlist.',               true, 0, null, null),
  ('outside',          'Outside',          'Music for the cookout, the block, and the great outdoors.',                true, 0, null, null),
  ('cookout',          'Cookout',          'Cookout season — the classics and the new joints.',                        true, 0, null, null),
  ('brunch',           'Brunch',           'Sunday brunch music — smooth, soulful, and vibey.',                       true, 0, null, null),
  ('club',             'Club',             'Club bangers — DJ sets, dance floor heat.',                                true, 0, null, null),
  ('turnt',            'Turnt',            'Turn up music — energy, hype, and good times.',                            true, 0, null, null),
  ('date-night',       'Date Night',       'Smooth, romantic, and setting the right mood.',                            true, 0, null, null),
  ('soft-life',        'Soft Life',        'Luxury vibes, self-care, and the soft life aesthetic.',                    true, 0, null, null),
  ('study-vibes',      'Study Vibes',      'Focus music — instrumentals, lo-fi, and background beats.',               true, 0, null, null),
  ('sunday-morning',   'Sunday Morning',   'Easy Sunday morning listening — gospel, jazz, soul.',                      true, 0, null, null),
  ('heartbreak',       'Heartbreak',       'The songs you listen to when it hurts.',                                   true, 0, null, null),
  ('hype',             'Hype',             'Motivational, high-energy, pre-game music.',                               true, 0, null, null),
  ('meditation',       'Meditation',       'Ambient, instrumental, and music for mindfulness.',                        true, 0, null, null),
  ('party',            'Party',            'Party music — hits, anthems, and crowd-pleasers.',                         true, 0, null, null),
  ('hbcu-vibes',       'HBCU Vibes',       'The HBCU experience — homecoming, yard, and culture.',                    true, 0, null, null),
  ('background-music', 'Background Music', 'Music that sets the mood without demanding attention.',                    true, 0, null, null)

ON CONFLICT (slug) DO UPDATE SET
  name        = EXCLUDED.name,
  description = EXCLUDED.description,
  is_official = EXCLUDED.is_official;
